---
terminator:
  config:
    global_config:
      inactive_color_offset: 0.7
    profiles:
      default:
        visible_bell: True
        scrollback_infinite: True
        # scrollback_lines: 5000

# excluded_apps_groups:
#   - media

# my_apps_groups:
#   addon:
#     apps:
#       - name: filezilla
#         type: apt

sudoers:
  enable: false

battery:
  enable: true
  percentage_low: 30
  percentage_critical: 10
  percentage_action: 5
  # Possible values are: PowerOff, Hibernate, HybridSleep
  critical_power_action: HybridSleep
