---
terminator:
  config:
    global_config:
      inactive_color_offset: 0.7
    profiles:
      default:
        visible_bell: True
        scrollback_infinite: True
        # scrollback_lines: 5000

excluded_apps_groups:
  - media

my_apps_groups:
  addon:
    apps:
      - name: filezilla
        type: apt
