#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: PatBriPerso
  description: Install phpenv.
  license: MIT
  min_ansible_version: 2.1
  galaxy_tags: 
    - phpenv
    - php

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
